import LikedMusic from '@/components/liked/liked'
import Head from 'next/head'
export default function Playlists() {
  return (
    <div>
      <Head>
        <title>Spotify- Liked Songs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LikedMusic />
    </div>
  )
}
