import PlaylistsIndex from '@/components/playlists/playlists'
import Head from 'next/head'
export default function Playlists() {
  return (
    <div>
      <Head>
        <title>My Playlists #1 - playlist by Edidiong Essien</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PlaylistsIndex />
    </div>
  )
}
