import Head from 'next/head'
import  '@/styles/Home.module.css'
import AuthIndex from '@/components/auth/Auth'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Sign up - Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthIndex />
    </div>
  )
}
