import Head from 'next/head'
import  '@/styles/Home.module.css'
import Login from '@/components/login/Login'
export default function LogInScreen() {
  return (
    <div>
      <Head>
        <title>Login - Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <AuthIndex /> */}
      <Login/>
    </div>
  )
}
