import SearchIndex from '@/components/search/Search'
import Head from 'next/head'
export default function Search() {
  return (
    <div>
      <Head>
        <title>Spotify - Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchIndex />
    </div>
  )
}
